name: Release

on:
  # Todo: use major, minor, patch labels on PRs to trigger releases, updating the info.json version
  # detect change in info.json version
  workflow_dispatch:
  workflow_call:

jobs:
  publish-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Mod
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: validate

      - name: Create zip
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: compress

          # TODO Upload to gh release as wel

      - name: Upload Mod
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: upload
          factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}
